### ISSUE TITLE
elm core blob error

### ISSUE THREAD

**Issue by CrashLaker** [harehare/textusm#2302]
Hi all,

is is possible to embed this o one's webiste?

i'm getting an weird elm error when trying to run the example code from https://www.npmjs.com/package/textusm

![image](https://user-images.githubusercontent.com/4432491/191908208-c1c65b6b-cd55-4459-ae0b-f22b59d8482c.png)

![image](https://user-images.githubusercontent.com/4432491/191908229-d9194922-d479-492e-877e-9c7a7a05bf89.png)

can anyone help me?

Regards,c.

**Comment by harehare** [comment]
Fixed in version 0.10.2.
