### ISSUE TITLE
[vscode-extension] export to png don't work

### ISSUE THREAD

**Issue by Chunters** [harehare/textusm#2982]
Hi, when i click export to png, application export to svg.
How export to png?

![image](https://github.com/harehare/textusm/assets/25099564/c811a5a3-d027-4dce-991a-ad4acd324060)

**Comment by jmorton05** [comment]
Same issue as mentioned, unable to export diagrams

**Comment by harehare** [comment]
Sorry for the delay in getting back to you about Issue #2982. 
fixed the issue in the latest commit.
