### ISSUE TITLE
Add cards.width and card.height options to VSCode extension

### ISSUE THREAD

**Issue by sukoyakarizumu** [harehare/textusm#467]
Hi hare, could you add cards.width and card.height options to VSCode extension?
We use VSCode live share extension to share and edit document each other.
We often writes a long sentence and it overflow a card.

**Comment by harehare** [comment]
Cards.width and card.height options added in https://github.com/harehare/textusm/commit/38a9bc92581fd2551eea2c31cb5329200ef6dd55
