### ISSUE TITLE
Unreliable output generation with CLI

### ISSUE THREAD

**Issue by jceb** [harehare/textusm#769]
I have a fairly large user story map with 160 entries in 21 user tasks. So I set a custom width and height to make it all visible. However, I noticed that the output picture varies in size. Maybe every third-to-fifth time I run the command to generate the output it falls back to the 1024x1024 size. This is also noticeable in the time it takes to run the command - when it fails it's twice as fast. It feels like an event is fired too early. However, no error message is displayed:

```
…/architecture on  master:origin/master [?]
↳ time textusm -w $(($(grep -e '^    [^ ]' user-story-map.txt|wc -l) * 156 + 160)) -H 3000 -d user_story_map -i user-story
-map.txt -o build/user-story-map.png

________________________________________________________
Executed in    1.80 secs   fish           external
   usr time  962.77 millis  537.00 micros  962.23 millis
   sys time  340.41 millis  184.00 micros  340.22 millis


…/architecture on  master:origin/master [?]
↳ time textusm -w $(($(grep -e '^    [^ ]' user-story-map.txt|wc -l) * 156 + 160)) -H 3000 -d user_story_map -i user-story
-map.txt -o build/user-story-map.png

________________________________________________________
Executed in    1.13 secs   fish           external
   usr time  530.15 millis  673.00 micros  529.48 millis
   sys time  311.40 millis  234.00 micros  311.17 millis
```

**Comment by harehare** [comment]
puppeteer.setViewport was not await.
Fixed https://github.com/harehare/textusm/commit/f1ced608a4a75c47f4b8c17d898f8950ea8f486d
