### ISSUE TITLE
Gantt diagram not working as the dates should be separated by spaces and not comas

### ISSUE THREAD

**Issue by michael-guimet** [harehare/textusm#779]
Awesome extension! Thanks for building it!

I'm having issues with the Gantt diagram displaying the example template on my MacOS 10.15.7. I look into it carefully and I think the issue is with the format of the example template.

I believe the comas in this template are breaking the opening of the Gantt diagram. Changing from comas to spaces seems to fix it. 

I am no developer, but I think I've tracked down the problem to this line:

https://github.com/harehare/textusm/blob/d7fe8558c8beb5d46dbb08fb0b4a81afa9527595/extension/vscode/src/extension.ts#L161

Additionally it opens the template twice.  No idea why.

Thanks again,

Michael

**Comment by harehare** [comment]
Thank you for bug report! I'll take a look into this shortly.

**Comment by harehare** [comment]
Fix https://github.com/harehare/textusm/commit/fabc58881b146c9b2bad619f28fe8a43cb44630f
