### ISSUE TITLE
VSCode extension works once and then you need to restart the editor to use it again

### ISSUE THREAD

**Issue by michael-guimet** [harehare/textusm#812]
Thanks again for the tool. Here is a bug I've found. 

Steps to reproduce:

1- In VSCode, use Open Preview or New Diagram, choose a diagram and complete process.
2- Try to use again and you can't select a diagram in the dropdown.

Versions:
MacOS 10.14.6
VSCode 1.53.2
TextUSM extension 0.6.73

Workaround: Relaunch VSCode and all works again

**Comment by harehare** [comment]
Thanks for the bug report!

**Comment by harehare** [comment]
Fix v0.6.74
https://marketplace.visualstudio.com/items?itemName=harehare.textusm
