### ISSUE TITLE
Reuse source file basename for image filenames

### ISSUE THREAD

**Issue by ngirard** [harehare/textusm#941]
Hi,
let me start by expressing my gratitude for your efforts into this nice project !

Using the latest released version of your VS Code extension, triggering e.g. `TextUSM: Export PNG` generates a file named `untitled.png`.
It would be nice if the basename `<b>` of the source file `path/to/<b>.txt` would be taken as the basename of the generated files -- in this case, that would be `<export_dir>/<b>.png`.

Cheers

**Comment by harehare** [comment]
Thanks for the bug report! 
Fix https://github.com/harehare/textusm/commit/5a1cf2aaa749245691c9f783d9ebc52a4f371543

**Comment by ngirard** [comment]
Thanks for your work !
Maybe nitpicking, but could you please consider removing the extension of the basename while reusing it ?
For instance, I'd expect TextUSM to generate `file.png` from `file.md` rather than `file.md.png`.
