### ISSUE TITLE
Allow for partial sets of styling parameters

### ISSUE THREAD

**Issue by ngirard** [harehare/textusm#943]
(Apologizes for the cryptic title of this report.)

When generating user story maps, most of the time I only need to change the background color of the cards.
Unfortunately, TextUSM chokes when supplying it with the sole `b` parameter, such as:

```
Level 1
    Level 2
        Level 3|{"b":"#EE8A8B"}
        Level 4|{"b":"#F7CAB2"}
```
For TextUSM to take into account the local styling, the whole set of parameters need to be supplied:
```
Level 1
    Level 2
        Level 3|{"b":"#EE8A8B","f":null,"o":[0,0],"s":14}
        Level 4|{"b":"#F7CAB2","f":null,"o":[0,0],"s":14}
```
It would be nice if only the `b` parameter could be supplied, because it would declutter the source file.
Cheers

**Comment by harehare** [comment]
thank you for your feedback!
Fix https://github.com/harehare/textusm/commit/41e06a7e6929a60d4438e101afe3fe196c3ca976

**Comment by ngirard** [comment]
Great ! Thank you very much for your dedication and responsiveness !
