### ISSUE TITLE
Allow to specify arbitrary colors

### ISSUE THREAD

**Issue by ngirard** [harehare/textusm#944]
Using the latest version of the TextUSM extension for VS Code on Ubuntu 20.04.

Unless I'm misunderstood, specifying arbitrary colors isn't currently supported.
For instance,
```
Level 1
    Level 2
        Level 3|{"b":"#EE8A8B","f":null,"o":[0,0],"s":14}
        Level 4|{"b":"#F7CAB2","f":null,"o":[0,0],"s":14}
```
works, because `#EE8A8B` and `#F7CAB2` belong to the set of acceptable colors, but
```
Level 1
    Level 2
        Level 3|{"b":"#00008B","f":null,"o":[0,0],"s":14}
        Level 4|{"b":"#00CA00","f":null,"o":[0,0],"s":14}
```
doesn't work and causes TextUSM to fall back to the default color.

Allowing to specify arbitrary colors beyond the predefined ones would be much useful.

**Comment by harehare** [comment]
thank you for your feedback!
Fix https://github.com/harehare/textusm/commit/7dc6b09b4f5c676278d2c35bcf62e5d3cd35babe

**Comment by ngirard** [comment]
Great, thanks !
