### ISSUE TITLE
TextUSM cli: configuration data has no effect on the output

### ISSUE THREAD

**Issue by ngirard** [harehare/textusm#948]
Using latest textusm.cli on Ubuntu 20.04.
Given this sample source file test.txt
```
A
    B
        D
        F
    C
        E
```
running `textusm -c config.json -o test.png -d user_story_map  < test.txt` renders the same output, no matter the contents of the `config.json` file.

I tried with the only two sets configurations that I could find, namely
- the one from https://www.npmjs.com/package/textusm.cli
- the one from https://www.npmjs.com/package/textusm -- with fixed contents (see #947)

The resulting file is exactly the same, no matter what is specified in `config.json`.
This problem is quite blocking for me.

**Comment by harehare** [comment]
Thank you for the bug report!
Fix https://github.com/harehare/textusm/commit/67df0cbc1e6b66842537a9b390e8c074e9ad19fb

**Comment by ngirard** [comment]
Nice ! Thank you so much !
