### ISSUE TITLE
TextUSM cli: ability to attach to a running headless chrome

### ISSUE THREAD

**Issue by ngirard** [harehare/textusm#953]
With the latest version of textusm, producing a single image takes ~7,5 seconds on my machine (Ubuntu 20.04):
```sh
time textusm --configFile config.json -o test.png -d user_story_map  < test.md 

real    0m7,476s
user    0m2,344s
sys     0m0,823s
```
This is quite long for my needs, which are to 1) generate maps on the fly when the source files are modified, and 2) share the maps with my coworkers so that we can have fruitful discussions around them and modify the source files as we are discussing.

Now, I'm afraid I can't be of much help with TextUSM's code itself, but I noticed that when installing TextUSM cli, one of its dependencies is chrome, so I'm assuming that TextUSM cli leverages a running headless instance of Chrome to produce its results.

If this assumption is correct, then I'm suggesting that TextUSM cli affers the ability to attach to an already running instance of Chrome.
The required steps for the user would be
1. Run Chrome in headless mode using e.g.
    ```sh
    chrome --remote-debugging-port=9222 --headless
    ```
2. When a source file `map.txt` is modified, run `textusm` and provide it with the usl of the running chrome instance, like
    ```sh
    textusm --cdp http://127.0.0.1:9222 --configFile config.json -o out.png -d user_story_map  < map.txt
    ```
(the suggested command-line semantics is borrowed from [Ferret](https://github.com/MontFerret/ferret) -- see section "Browser mode" in https://www.montferret.dev/docs/getting-started).

This added capability should allow to considerably reduce the generation times.

**Comment by harehare** [comment]
Thanks for the your feedback.
added the cdp option to the cli.
https://github.com/harehare/textusm/commit/6a18d76d2e230cea61cbdb59119ce4ab3d17c484

**Comment by ngirard** [comment]
Wow ! Thank you so much !
I'll try to test it as soon as I can !

**Comment by ngirard** [comment]
Reporting back...
The time needed to produce an image went down from ~7.5 to 2.5 seconds on my machine.
Great work, thanks again !

**Comment by ngirard** [comment]
@harehare,
unfortunately when attaching to a running headless Chrome, each invocation of Textusm increases the number of chrome subprocess (ultimately exhausting my machine's virtual memory).

Maybe I should file a new issue for that ?
